---
file_cache_path: /var/cache
source_functions_library: /etc/init.d/functions
org_name: None
banner: "Default banner"
domain_name: None
firewall_zone: None
firewall_enabled: true
timezone: 'Asia/Kolkata'
primary_server: None
root_user: root
root_group: root