---
user_name: root
group_name: root
home_dir: /root

source_functions_library: /etc/init.d/functions

var: 
  cache: 
    path: /var/cache 

ntp:
  package_name: ntp 
  package_version: 4.2.6p5
  service_name: ntpd
jdk:
  package_name: java-1.7.0-openjdk
  package_version: 1.7.0.79

mysql:
  packages:
    - mysql-server
    - mysql-client
    - libmysqlclient-dev
    - libdbd-mysql
    - python-mysqldb
apache:
  package_name: httpd
  service_name: httpd
  base_directory: /etc/httpd
  service_owner: httpd
  group_owner: httpd

    